# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Moneta' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
# Log
  pod 'CocoaLumberjack/Swift'
# UI
  pod 'SnapKit', '~> 5.6.0'
  pod 'Kingfisher', '~> 7.0'
# Net
  pod 'Moya', '~> 15.0'
# ORM
  pod 'HandyJSON'
# Project


  # Pods for Moneta

end
